
#line 3 "glb_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
       64,   64,   17,   17,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
        5,    5,    2,    2,    0,    0,   69,   66,   64,   67,
       34,   66,   66,   66,   66,   66,   55,   44,   45,   62,
       23,   24,   62,   25,   62,   23,   62,   62,   62,   62,
       18,   17,   68,   19,   53,   45,   21,   22,   45,   45,
       45,   45,   45,   66,   66,   66,   66,   66,   66,    5,
        7,    6,    2,    3,   36,   35,   37,   64,   52,   52,
       56,   56,    0,   63,   58,    4,    1,   57,   55,    0,

       62,   23,   24,   62,   25,   62,   62,   23,   62,   62,
       62,   62,   18,   17,   54,   54,   54,   54,   54,   54,
       54,   54,   46,   46,   47,   47,   48,   48,   49,   49,
       50,   50,   51,   51,    5,    6,    6,    8,    2,   37,
       52,   52,   56,   56,    0,   63,    0,   57,    0,    0,
       61,   62,   62,   62,   23,   62,   62,   62,   62,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   46,   46,
       47,   47,   48,   48,   49,   49,   50,   50,   51,   51,
       52,   56,    0,    0,   60,    0,   59,   62,   62,   62,
       23,   14,   62,   62,   10,   54,   54,   54,   54,   54,

       54,   54,   54,   46,   47,   48,   49,   50,   51,   52,
       56,    0,   62,   62,   13,   62,   62,   62,   54,   54,
       54,   54,   54,   54,   54,   54,   46,   47,   48,   49,
       50,   51,    9,   56,    0,   26,   27,   28,   62,   12,
       62,   15,   54,   54,   54,   54,   54,   54,   54,   54,
       56,    0,   26,   27,   28,   11,   16,   54,   30,   54,
       54,   54,   29,   54,   54,   54,   38,   65,   54,   54,
       54,   20,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   40,   42,   31,   54,   54,
       39,   54,   54,   54,   54,   41,   43,   54,   54,   54,

       54,   54,   54,   54,   32,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    1,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,   16,
        1,   17,    1,   18,   19,   20,   21,   22,   23,   22,
       24,   22,   22,   22,   22,   25,   26,   27,   28,   22,
       22,   29,   30,   31,   32,   22,   22,   33,   22,   22,
        1,    1,    1,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   22,   44,   45,   46,   47,
       48,   22,   22,   49,   50,   51,   52,   53,   22,   54,
       55,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    5,    1,
        6,    6,    6,    7,    1,    1,    1,    1,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static yyconst flex_int16_t yy_base[338] =
    {   0,
        0,    0,   54,   56,   23,   27,   61,   65,  105,  145,
      101,  141,  156,  181,  192,  196,  207,  232,   87,  221,
      236,  247,  251,  268,  272,  283,  287,  298,  304,  319,
       62,   66,  661,  660,  368,  402,  662,  665,  659,  665,
      665,  633,  606,  654,  643,   71,   74,  665,  665,    0,
      416,  119,  628,  245,   19,  608,  609,  606,  600,  599,
        0,  648,  665,  665,  665,   37,  665,  665,  612,  609,
      610,  606,  605,  617,  616,  615,  614,  613,  612,    0,
      665,   76,    0,  665,  665,  665,    0,  636,    0,  614,
        0,  597,  611,    0,  114,  665,  665,  163,  177,   80,

        0,    0,  402,  604,  329,  598,  584,  592,  578,  592,
      588,  582,    0,  624,    0,  590,   52,  582,  576,  573,
      576,  575,    0,  568,    0,  560,    0,  554,    0,  552,
        0,  544,    0,  543,    0,   83,   90,  665,    0,    0,
        0,  528,    0,  511,  534,    0,  119,  326,  121,  510,
      506,  497,  470,  466,  466,  460,  465,  464,  467,    0,
      467,  459,  448,  461,  454,  443,  438,  434,    0,  452,
        0,  451,    0,  450,    0,  448,    0,  447,    0,  445,
      446,  425,  425,  456,  454,  446,  444,  423,  401,  392,
      399,    0,  386,  383,    0,  389,  385,  397,  381,  378,

      376,  371,  370,  392,  391,  390,  385,  383,  370,  394,
      356,  377,  443,  357,    0,  339,  355,  338,  350,  355,
      341,  341,  346,  330,  333,  329,  356,  354,  351,  349,
      348,  346,  665,  302,  323,  474,  424,  363,  297,    0,
      300,    0,  284,  286,  128,  290,  273,  284,  276,  274,
      266,  276,    0,  460,  427,    0,    0,  255,    0,  262,
      267,  254,    0,  255,  249,  239,    0,  665,  215,  232,
      225,    0,  220,  217,  214,  208,  212,  199,  195,  199,
      198,  196,  174,  175,  180,  183,  181,    0,  164,  170,
        0,  160,  158,  164,  136,    0,    0,  132,  136,  133,

      122,  121,  118,  117,    0,    0,  665,  525,  533,  541,
      549,  152,  141,  554,  556,  564,  135,  131,  117,  112,
      103,  101,   98,  572,  580,  588,  591,  593,  595,  597,
      599,  601,  603,  605,  607,  609,  611
    } ;

static yyconst flex_int16_t yy_def[338] =
    {   0,
      307,    1,  308,  308,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
      309,  309,  310,  310,  311,  311,  307,  307,  307,  307,
      307,  312,  313,  314,  307,  307,  307,  307,  307,  315,
      315,  315,  315,  315,  315,   51,  315,  315,  315,  315,
      316,  307,  307,  307,  307,  317,  307,  307,  317,  317,
      317,  317,  317,  318,  319,  320,  321,  322,  323,  324,
      307,  325,  326,  307,  307,  307,  327,  307,  328,  328,
      329,  329,  307,  330,  307,  307,  307,  307,  307,  307,

      315,   51,  315,  315,  315,  315,  315,   51,  315,  315,
      315,  315,  316,  307,  331,  331,  331,  331,  331,  331,
      331,  331,  332,  332,  333,  333,  334,  334,  335,  335,
      336,  336,  337,  337,  324,  325,  325,  307,  326,  327,
      328,  328,  329,  329,  307,  330,  307,  307,  307,  307,
      307,  315,  315,  315,   51,  315,  315,  315,  315,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  332,  332,
      333,  333,  334,  334,  335,  335,  336,  336,  337,  337,
      328,  329,  307,  307,  307,  307,  307,  315,  315,  315,
       51,  315,  315,  315,  315,  331,  331,  331,  331,  331,

      331,  331,  331,  332,  333,  334,  335,  336,  337,  328,
      329,  307,  315,  315,  315,  315,  315,  315,  331,  331,
      331,  331,  331,  331,  331,  331,  332,  333,  334,  335,
      336,  337,  307,  329,  307,  315,  315,  315,  315,  315,
      315,  315,  331,  331,  331,  331,  331,  331,  331,  331,
      329,  307,  236,  315,  315,  315,  315,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  329,  307,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,

      331,  331,  331,  331,  331,  331,    0,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_nxt[721] =
    {   0,
       38,   39,   40,   38,   41,   42,   43,   44,   38,   38,
       38,   45,   46,   47,   48,   38,   38,   49,   50,   50,
       50,   50,   51,   50,   50,   52,   53,   50,   50,   50,
       54,   50,   50,   38,   50,   50,   55,   50,   56,   57,
       50,   50,   58,   50,   50,   52,   59,   50,   60,   50,
       54,   50,   50,   50,   50,   62,   63,   62,   63,   50,
      106,   51,   50,   50,   81,   51,   50,  107,   81,   50,
       82,   50,  116,   50,   82,   50,   64,   65,   66,   96,
       64,   65,   66,   97,  137,   98,  117,   99,  138,  150,
      150,  307,   74,  151,  162,  307,  100,   50,  137,   51,

       50,   50,  138,   51,   50,  133,  163,   50,  131,   50,
      129,   50,  100,   50,   67,   68,   64,   65,   70,  127,
       64,   65,   69,   50,  125,   51,   50,   95,  184,  184,
      186,  186,  185,   50,  187,   50,  147,   50,  123,   51,
       50,   50,  115,   51,   50,  103,  103,   50,   91,   50,
      103,   50,  147,   50,   67,   68,   64,   65,   70,   89,
       64,   65,   69,  306,  305,  103,  103,  260,  304,  303,
      103,   64,   65,   71,  261,  302,  148,   50,  301,   51,
       50,   50,  300,   51,   50,  149,  299,   50,   98,   50,
       99,   50,   50,   50,   51,   50,   64,   65,   71,  100,

      298,  149,   50,  297,   50,  296,  295,   64,   65,   72,
      294,   64,   65,   72,  293,  100,  292,   50,  291,   51,
       50,  290,   64,   65,   73,  289,   74,   50,   50,   50,
       51,   50,   50,  288,   51,   50,  287,  286,   50,  285,
       50,   75,   50,   50,   50,   51,   50,   64,   65,   73,
      284,  283,   75,   50,  282,   50,   76,   50,  281,   51,
       50,  280,  279,  105,  278,  277,  276,   50,   50,   50,
       51,   50,   50,   76,   51,   50,  105,   77,   50,  105,
       50,  275,   50,   50,   50,   51,   50,   50,   77,   51,
       50,  274,   78,   50,  273,   50,  105,   50,  272,   50,

      271,  270,  269,   78,   50,  268,   51,   50,   50,   79,
       51,   50,  267,  266,   50,  265,   50,  264,   50,   50,
       50,   51,   50,   50,   79,   51,   50,  263,  262,   50,
      259,   50,  258,   50,   50,   50,   51,   50,  257,  148,
       50,  256,   51,   50,   50,  252,   50,  105,  149,  251,
       50,  233,   50,  233,  233,   50,  233,   51,   50,  233,
      105,  233,  250,  105,  149,   50,  249,   50,   63,   63,
       85,   63,   86,   63,   63,   63,   63,   63,   63,  248,
      105,  255,   63,   63,   63,   63,  247,  246,  245,  244,
      243,  242,  241,  240,  255,  239,  235,  255,  234,  233,

      232,   63,   63,   63,   85,   63,   86,   63,   63,   63,
       63,   63,   63,  231,  255,  230,   63,   63,   63,   63,
      229,  228,  227,  226,  225,  224,  223,  222,  103,  103,
      221,  220,  219,  103,  218,   63,  102,  217,  102,  216,
      102,  215,  102,  102,  102,  255,  102,  214,  103,  103,
      254,  254,  102,  103,  102,  254,  213,  187,  255,  187,
      102,  255,  102,  102,  102,  236,  102,  185,  237,  185,
      254,  254,  212,  238,  211,  254,  210,  209,  255,  208,
      207,  236,  206,  205,  204,  203,  254,  254,  237,  202,
      201,  254,  200,  238,  253,  199,  253,  198,  253,  197,

      253,  253,  253,  196,  253,  195,  254,  254,  194,  193,
      253,  254,  253,  192,  191,  190,  189,  188,  253,  151,
      253,  253,  253,  151,  253,   61,   61,   61,   61,   61,
       61,   61,   61,   80,   80,   80,   80,   80,   80,   80,
       80,   83,   83,   83,   83,   83,   83,   83,   83,   87,
       87,   87,   87,   87,   87,   87,   87,   94,  183,  182,
      181,   94,  101,  101,  113,  180,  178,  113,  113,  113,
      113,  113,  135,  135,  176,  135,  174,  135,  135,  135,
      136,  136,  172,  136,  136,  136,  136,  136,  139,  139,
      170,  139,  139,  139,  139,  139,  140,  140,  140,  141,

      141,  143,  143,  146,  146,  160,  160,  169,  169,  171,
      171,  173,  173,  175,  175,  177,  177,  179,  179,  168,
      167,  166,  165,  164,  161,  114,  159,  158,  157,  156,
      155,  154,  153,  152,  145,  144,  142,   88,  134,  132,
      130,  128,  126,  124,  122,  121,  120,  119,  118,  114,
      112,  111,  110,  109,  108,  104,   95,   93,   92,   90,
       88,  307,   84,   84,   37,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[721] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    5,
       55,    5,    5,    6,   31,    6,    6,   55,   32,    5,
       31,    5,   66,    6,   32,    6,    7,    7,    7,   46,
        8,    8,    8,   46,   82,   47,   66,   47,   82,  100,
      100,  136,   19,  100,  117,  136,   47,    7,  137,    7,

        7,    8,  137,    8,    8,  323,  117,    7,  322,    7,
      321,    8,   47,    8,    9,    9,   11,   11,   11,  320,
        9,    9,    9,   19,  319,   19,   19,   95,  147,  147,
      149,  149,  147,   19,  149,   19,   95,   11,  318,   11,
       11,    9,  317,    9,    9,   52,   52,   11,  313,   11,
       52,    9,   95,    9,   10,   10,   12,   12,   12,  312,
       10,   10,   10,  304,  303,   52,   52,  245,  302,  301,
       52,   13,   13,   13,  245,  300,   98,   12,  299,   12,
       12,   10,  298,   10,   10,   98,  295,   12,   99,   12,
       99,   10,   13,   10,   13,   13,   14,   14,   14,   99,

      294,   98,   13,  293,   13,  292,  290,   15,   15,   15,
      289,   16,   16,   16,  287,   99,  286,   14,  285,   14,
       14,  284,   17,   17,   17,  283,   20,   14,   15,   14,
       15,   15,   16,  282,   16,   16,  281,  280,   15,  279,
       15,   21,   16,   17,   16,   17,   17,   18,   18,   18,
      278,  277,   22,   17,  276,   17,   23,   20,  275,   20,
       20,  274,  273,   54,  271,  270,  269,   20,   18,   20,
       18,   18,   21,   24,   21,   21,   54,   25,   18,   54,
       18,  266,   21,   22,   21,   22,   22,   23,   26,   23,
       23,  265,   27,   22,  264,   22,   54,   23,  262,   23,

      261,  260,  258,   28,   24,  252,   24,   24,   25,   29,
       25,   25,  251,  250,   24,  249,   24,  248,   25,   26,
       25,   26,   26,   27,   30,   27,   27,  247,  246,   26,
      244,   26,  243,   27,   28,   27,   28,   28,  241,  148,
       29,  239,   29,   29,   28,  235,   28,  105,  148,  234,
       29,  232,   29,  231,  230,   30,  229,   30,   30,  228,
      105,  227,  226,  105,  148,   30,  225,   30,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,  224,
      105,  238,   35,   35,   35,   35,  223,  222,  221,  220,
      219,  218,  217,  216,  238,  214,  212,  238,  211,  210,

      209,   35,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,  208,  238,  207,   36,   36,   36,   36,
      206,  205,  204,  203,  202,  201,  200,  199,  103,  103,
      198,  197,  196,  103,  194,   36,   51,  193,   51,  191,
       51,  190,   51,   51,   51,  255,   51,  189,  103,  103,
      237,  237,   51,  103,   51,  237,  188,  187,  255,  186,
       51,  255,   51,   51,   51,  213,   51,  185,  213,  184,
      237,  237,  183,  213,  182,  237,  181,  180,  255,  178,
      176,  213,  174,  172,  170,  168,  254,  254,  213,  167,
      166,  254,  165,  213,  236,  164,  236,  163,  236,  162,

      236,  236,  236,  161,  236,  159,  254,  254,  158,  157,
      236,  254,  236,  156,  155,  154,  153,  152,  236,  151,
      236,  236,  236,  150,  236,  308,  308,  308,  308,  308,
      308,  308,  308,  309,  309,  309,  309,  309,  309,  309,
      309,  310,  310,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  311,  311,  311,  311,  314,  145,  144,
      142,  314,  315,  315,  316,  134,  132,  316,  316,  316,
      316,  316,  324,  324,  130,  324,  128,  324,  324,  324,
      325,  325,  126,  325,  325,  325,  325,  325,  326,  326,
      124,  326,  326,  326,  326,  326,  327,  327,  327,  328,

      328,  329,  329,  330,  330,  331,  331,  332,  332,  333,
      333,  334,  334,  335,  335,  336,  336,  337,  337,  122,
      121,  120,  119,  118,  116,  114,  112,  111,  110,  109,
      108,  107,  106,  104,   93,   92,   90,   88,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   69,   62,
       60,   59,   58,   57,   56,   53,   45,   44,   43,   42,
       39,   37,   34,   33,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "glb_lexer.l"
/* GLoBES -- General LOng Baseline Experiment Simulator
 * (C) 2002 - 2007,  The GLoBES Team
 *
 * GLoBES is mainly intended for academic purposes. Proper
 * credit must be given if you use GLoBES or parts of it. Please
 * read the section 'Credit' in the README file.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/* This here caused an unpleasant problem:
 * things like
 * %s rule
 * would cause a 
 * #define rule xxx
 * statement in glb_lexer.c and that in turn causes
 * trouble with inlcude files which contain
 * glbXXX(int rule)
 * because this will be expanded by the preprocessor to
 * glbXXX(int xxx)
 * which then causes a stupid error of the form
 * parse error before numeric constant
 * The flex manual says that these things have global scope
 * but as usual I read the manual after the fact
 * PH
 */

















#line 68 "glb_lexer.l"
/* need this for the call to atof() below */
#include <math.h>
#include <string.h>

#include "glb_parser_type.h"
#include "glb_parser.h"
#include "glb_error.h"


 #define MAX_INCLUDE_DEPTH 10
static YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
static int include_stack_ptr = 0;
int glb_line_num=0;
char *glb_file_id;
static int line_buf[MAX_INCLUDE_DEPTH];
static char *file_name_buf[MAX_INCLUDE_DEPTH];
static int cond_buf; 
/* I am not sure wether this works with nested contexts */
static int cond_buf_i; 
static int cond_buf_str; 
static char *fnbuf,*fnbuf2;
static size_t len,i;

void glb_lexer_cleanup();


#line 792 "glb_lexer.c"

#define INITIAL 0
#define glb_lexer_incl 1
#define glb_lexer_grp 2
#define glb_lexer_rule 3
#define glb_lexer_chl 4
#define glb_lexer_energy 5
#define glb_lexer_cross 6
#define glb_lexer_flux 7
#define glb_lexer_nuflux 8
#define glb_lexer_defr 9
#define glb_lexer_defc 10
#define glb_lexer_defe 11
#define glb_lexer_defx 12
#define glb_lexer_deff 13
#define glb_lexer_defnf 14
#define glb_lexer_comment 15
#define glb_lexer_linecomment 16
#define glb_lexer_str 17

/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 106 "glb_lexer.l"


#line 961 "glb_lexer.c"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 665 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "glb_lexer.l"
{cond_buf=YY_START;BEGIN(glb_lexer_linecomment);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 "glb_lexer.l"
/* eat anything that's not a '\n' */
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 110 "glb_lexer.l"
{++glb_line_num; BEGIN(cond_buf);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "glb_lexer.l"
{cond_buf=YY_START;BEGIN(glb_lexer_comment);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "glb_lexer.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "glb_lexer.l"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 115 "glb_lexer.l"
++glb_line_num;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 116 "glb_lexer.l"
BEGIN(cond_buf);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 118 "glb_lexer.l"
{
glb_copy_buff();
glbReset();
}
	YY_BREAK

case 10:
YY_RULE_SETUP
#line 125 "glb_lexer.l"
{BEGIN(glb_lexer_defr);yylval.name=yytext;return GID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 126 "glb_lexer.l"
{BEGIN(glb_lexer_defc);yylval.name=yytext;return GID;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "glb_lexer.l"
{BEGIN(glb_lexer_defe);yylval.name=yytext;return GID;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 128 "glb_lexer.l"
{BEGIN(glb_lexer_defx);yylval.name=yytext;return GID;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 "glb_lexer.l"
{BEGIN(glb_lexer_deff);yylval.name=yytext;return GID;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 130 "glb_lexer.l"
{BEGIN(glb_lexer_defnf);yylval.name=yytext;return GID;}
	YY_BREAK

case 16:
YY_RULE_SETUP
#line 133 "glb_lexer.l"
{cond_buf_i=YY_START;BEGIN(glb_lexer_incl);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "glb_lexer.l"
/* eat the whitespace */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "glb_lexer.l"
{ /* got the include file name */
if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
{
fprintf( stderr, "FATAL: Includes nested too deeply\n" );
exit( 1 );
}

if(include_stack_ptr==0) 
{
file_name_buf[include_stack_ptr]=glb_file_id;
line_buf[include_stack_ptr]=glb_line_num;
}



include_stack[include_stack_ptr++] =
YY_CURRENT_BUFFER;

fnbuf=strdup(yytext);
len=strlen(fnbuf);
if(fnbuf[len-1]!='\"') {fprintf(stderr,"FATAL:" 
" Unterminated filename\n");exit(1) ;}
if(fnbuf[0]!='\"') {fprintf(stderr,"FATAL:" 
" Unquoted filename\n");exit(1) ;}
fnbuf2=(char *) glb_malloc((len-1)*sizeof(char));
for(i=0;i<len-1;i++) fnbuf2[i]=fnbuf[i+1];
fnbuf2[len-2]='\0';
yyin = glb_fopen( fnbuf2, "r" );

if ( ! yyin ){
fprintf(stderr,"FATAL: Could not open file %s\n",fnbuf2);exit(1);}

file_name_buf[include_stack_ptr]=(char*) strdup(fnbuf2);
glb_file_id=file_name_buf[include_stack_ptr];
line_buf[include_stack_ptr]=glb_line_num;
glb_line_num=0;
glb_free(fnbuf);
glb_free(fnbuf2);

yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE ) );


BEGIN(cond_buf_i);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(glb_lexer_incl):
case YY_STATE_EOF(glb_lexer_grp):
case YY_STATE_EOF(glb_lexer_rule):
case YY_STATE_EOF(glb_lexer_chl):
case YY_STATE_EOF(glb_lexer_energy):
case YY_STATE_EOF(glb_lexer_cross):
case YY_STATE_EOF(glb_lexer_flux):
case YY_STATE_EOF(glb_lexer_nuflux):
case YY_STATE_EOF(glb_lexer_defr):
case YY_STATE_EOF(glb_lexer_defc):
case YY_STATE_EOF(glb_lexer_defe):
case YY_STATE_EOF(glb_lexer_defx):
case YY_STATE_EOF(glb_lexer_deff):
case YY_STATE_EOF(glb_lexer_defnf):
case YY_STATE_EOF(glb_lexer_comment):
case YY_STATE_EOF(glb_lexer_linecomment):
case YY_STATE_EOF(glb_lexer_str):
#line 184 "glb_lexer.l"
{ if ( --include_stack_ptr < 0 )
{
glb_copy_buff();
glbReset();
/* BUGFIX #9 -- This lines fixes a tricky bug in the parser */
include_stack_ptr=0;
yyterminate();
}
else
{
glb_fclose(yyin);
yy_delete_buffer(YY_CURRENT_BUFFER );
yy_switch_to_buffer(include_stack[include_stack_ptr] );
glb_line_num=line_buf[include_stack_ptr];
glb_file_id=file_name_buf[include_stack_ptr];
}
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 204 "glb_lexer.l"
{
yylval.name=yytext;

return GRPOPEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 209 "glb_lexer.l"
{
yylval.name=yytext;

return CHANNEL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 214 "glb_lexer.l"
{yylval.in=+1;return PM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 215 "glb_lexer.l"
{yylval.in=-1;return PM;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 217 "glb_lexer.l"
{yylval.in=1;return FLAVOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 218 "glb_lexer.l"
{yylval.in=2;return FLAVOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 219 "glb_lexer.l"
{yylval.in=3;return FLAVOR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 221 "glb_lexer.l"
{yylval.in=11;return FLAVOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 222 "glb_lexer.l"
{yylval.in=12;return FLAVOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 223 "glb_lexer.l"
{yylval.in=13;return FLAVOR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 226 "glb_lexer.l"
{
yylval.name=yytext;

return ENERGY;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 231 "glb_lexer.l"
{
yylval.name=yytext;

return SIGNAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 236 "glb_lexer.l"
{
yylval.name=yytext;

return BG;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 241 "glb_lexer.l"
{
yylval.name=yytext;
return SYS_ON_FUNCTION;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 246 "glb_lexer.l"
{
yylval.name=yytext;
return SYS_OFF_FUNCTION;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 253 "glb_lexer.l"
{cond_buf_str=YY_START;BEGIN(glb_lexer_str);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 255 "glb_lexer.l"
{BEGIN(cond_buf_str);}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 257 "glb_lexer.l"
{glb_fatal("Lexer error: Unterminated string");exit(1);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 259 "glb_lexer.l"
{
yylval.name=yytext;
return FNAME;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 263 "glb_lexer.l"
{
yylval.name=yytext;
return VERS;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 268 "glb_lexer.l"
{
yylval.name=yytext;
return CROSS;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 272 "glb_lexer.l"
{
yylval.name=yytext;
return FLUXP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 277 "glb_lexer.l"
{
yylval.name=yytext;
return FLUXM;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 284 "glb_lexer.l"
{
yylval.name=yytext;
return NUFLUX;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 289 "glb_lexer.l"
{
yylval.name=yytext;
return NUFLUX;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 294 "glb_lexer.l"
{return RULESEP;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 295 "glb_lexer.l"
{return RULEMULT;} 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 299 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) 
s = glb_putname (yytext,"rule",NAME); 
BEGIN(INITIAL);
BEGIN(glb_lexer_rule); 
if(strcmp(s->context,"rule")!=0) 
{yylval.nameptr=s;return RDF;}

yylval.nameptr = s; 

return s->type;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 313 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"channel");
if (s == 0) 
s = glb_putname (yytext,"channel",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_chl); 
if(strcmp(s->context,"channel")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s;  

return s->type;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 327 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"energy");
if (s == 0) 
s = glb_putname (yytext,"energy",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_energy);
if(strcmp(s->context,"energy")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 341 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"cross");
if (s == 0) 
s = glb_putname (yytext,"cross",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_cross);
if(strcmp(s->context,"cross")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 356 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"flux");
if (s == 0) 
s = glb_putname (yytext,"flux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_flux);
if(strcmp(s->context,"flux")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 370 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"nuflux");
if (s == 0) 
s = glb_putname (yytext,"nuflux",NAME);
BEGIN(INITIAL);
BEGIN(glb_lexer_nuflux);
if(strcmp(s->context,"nuflux")!=0) 
{yylval.nameptr=s;return RDF;}
 
yylval.nameptr = s; 
 
return s->type;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 384 "glb_lexer.l"
{glb_namerec *s;
s = glb_getname (yytext,"rule");
if (s == 0) return NDEF;
yylval.nameptr = s; 
return s->type; 
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 391 "glb_lexer.l"
{
BEGIN(INITIAL);
return GRPCLOSE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 396 "glb_lexer.l"
{
yylval.name=yytext;
return IDN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 404 "glb_lexer.l"
{yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 408 "glb_lexer.l"
{yylval.name=yytext;return IDN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 410 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 415 "glb_lexer.l"
{
 yylval.val=atof(yytext); 
 return NUM;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 420 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 425 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 430 "glb_lexer.l"
{
yylval.val=atof(yytext); 
return NUM;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 438 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0) 
s = glb_putsym (yytext, VAR); 
yylval.tptr = s; 
return s->type; 
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 447 "glb_lexer.l"
{glb_symrec *s;
s = glb_getsym (yytext);
if (s == 0) 
s = glb_putsym (yytext, LVAR); 
yylval.tptr = s; 
return s->type; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 459 "glb_lexer.l"
/* eat up whitespace */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 461 "glb_lexer.l"
/* empty */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 463 "glb_lexer.l"
return (int) yytext[0];
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 466 "glb_lexer.l"
/* yylloc.first_line++;*/ glb_line_num++; return '\n';
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 467 "glb_lexer.l"
ECHO;
	YY_BREAK
#line 1620 "glb_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * str )
{
    
	return yy_scan_bytes(str,strlen(str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 467 "glb_lexer.l"




/* OLD CODE, DOES NOT RUN WITH NEWER FLEX VERSIONS ANYMORE [WW, JK]:

void glb_lexer_cleanup() {
     if( yy_current_buffer != NULL )
     {
         yy_delete_buffer(yy_current_buffer );
         yy_current_buffer = 0;
     }
}
*/



void glb_lexer_cleanup() {
      if( YY_CURRENT_BUFFER != NULL )
          yy_delete_buffer(YY_CURRENT_BUFFER );
}



